const eventData = [
    {
      img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202023%202.0/WhatsApp%20Image%202023-10-22%20at%2022.18.12_a776bd51.jpg?updatedAt=1704172927773",
      content: "The AI/Metaverse Workshop, organized by the Department of Artificial Intelligence and Data Science at Jyothi Engineering College in collaboration with AIDA and Unique World Robotics, was held on October 28th at the Decennial Hall. The event was a grand success, featuring a keynote address by Akhila R Gomez, Head of Academic Innovations at Unique World Robotics. Attendees gained valuable insights into the latest trends in Artificial Intelligence and the Metaverse. The engaging sessions and interactive discussions left the attendees inspired and eager to explore further in the field of AI and Metaverse technologies."
    },
    {
      img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202024/AIDA%20cybersecurity%20Workshop.png?updatedAt=1738224633267",
      content: "The Cybersecurity Workshop conducted by AIDA at Jyothi Engineering College was a valuable and insightful event for all participants. The workshop provided an in-depth understanding of various cybersecurity threats and protective measures. The positive feedback from participants highlighted the workshop's success in raising awareness and preparedness against cybersecurity challenges. Overall, the event was a resounding success, leaving attendees equipped with essential skills to navigate the evolving landscape of cybersecurity"
    },
    {
      img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202024/Idea%20Ignite%20Poster%20(9x16).jpg?updatedAt=1738224631360",
      content: "The IDEA IGNITE event, organized by AIDA at Jyothi Engineering College, showcased the innovative and creative talents of students. Participants presented their groundbreaking ideas and projects, aiming to solve real-world problems and contribute to technological advancements. The event provided a platform for students to demonstrate their ingenuity and critical thinking skills. With a competitive atmosphere, students vied for attractive prizes by impressing the judges with their unique concepts and presentations. The enthusiasm and excitement were palpable, making IDEA IGNITE a memorable and successful event"
    },
    {
        img: "https://ik.imagekit.io/AIDA/Past%20Events/aida%20inaguration/AIDA_INAUGURATION.jpg?updatedAt=1738226467691" ,
        content: "The inauguration of the Artificial Intelligence and Data Science Association (AIDA) club at Jyothi Engineering College for the academic year 2022 was a noteworthy event that marked the beginning of a new chapter of innovation and learning. The ceremony featured inspiring speeches by distinguished guests, faculty members, and student representatives. The event highlighted the club's mission to foster a deeper understanding of AI and data analytics among students. Participants were introduced to the club's planned activities, workshops, and events aimed at enhancing their technical skills and knowledge in these rapidly evolving fields. The inauguration was well-attended, and the enthusiasm and excitement among the students set a positive tone for the upcoming academic year."
    },
    {
        img: "https://ik.imagekit.io/AIDA/Past%20Events/aida%20inaguration/Our%20Artificial%20Intelligence%20and%20Data%20Science%20Association%20has%20officially%20been%20Inaugurated..jpg?updatedAt=1738226430139",
        content: "The inauguration of the Artificial Intelligence and Data Science Association (AIDA) club at Jyothi Engineering College for the academic year 2023 was an exciting and memorable event. The ceremony featured inspiring speeches from distinguished guests, faculty members, and student representatives, who emphasized the importance of AI and data analytics in today's world. The event highlighted the club's mission to promote learning, innovation, and collaboration among students. Attendees were introduced to the club's planned activities, workshops, and events for the year, all designed to enhance their technical skills and knowledge. The inauguration was well-received, with a high level of enthusiasm and participation from students."
    },
    {
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202023/Workshop-min.png?updatedAt=1697130368256" ,
        content: "The Introduction to Web3 and Blockchain Technology Workshop, organized by AIDA at Jyothi Engineering College, was an informative and engaging event. The workshop provided participants with a foundational understanding of Web3 and blockchain technology, exploring their potential applications and impact on various industries. Attendees engaged in hands-on activities and interactive sessions, which greatly enhanced their practical skills and knowledge in these emerging technologies. The workshop received positive feedback from participants, highlighting its success in demystifying complex concepts and inspiring further exploration into the world of Web3 and blockchain."
    },
    {
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Other%20Events/Neophyte%20Poster.png?updatedAt=1738226589964",
        content: "The NEOPHYTE Hackathon, organized by AIDA at Jyothi Engineering College, was an exciting and educational event tailored for beginners. The hackathon aimed to introduce novice participants to the world of competitive programming and project development. Over the course of the event, attendees worked collaboratively in teams to develop innovative solutions to real-world problems. The supportive environment and mentorship provided by experienced professionals helped participants enhance their coding skills and gain confidence in their abilities. The event culminated in impressive project presentations, with the top teams being awarded attractive prizes."
    },
    {
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202023%202.0/Mini-Games.jpg?updatedAt=1704172928111",
        content: "The PEDAL AND PLAY event, organized by AIDA at Jyothi Engineering College during THARANG, was a thrilling and action-packed spectacle. The event featured various performers showcasing their incredible bike stunt skills, leaving the audience in awe with their daring and precision. The atmosphere was electric as participants executed jaw-dropping tricks and stunts, demonstrating their expertise and passion for extreme sports. The event was well-received, with enthusiastic applause and cheers from the crowd, highlighting the immense talent and dedication of the performers"
    },
    {
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202023%202.0/WhatsApp%20Image%202023-11-16%20at%2020.15.54%20(1).jpeg?updatedAt=1704172928435",
        content: "The RAZZLE DAZZLE event, organized by AIDA at Jyothi Engineering College during THARANG, was a vibrant and dynamic showcase of talent. Participants had the opportunity to perform and demonstrate their various skills, ranging from singing and playing instruments to dancing and other artistic expressions. The event was a celebration of creativity and individuality, providing a platform for students to shine and share their unique talents with a supportive audience. The diverse performances captivated and entertained the audience, creating an atmosphere of excitement and inspiration"
    },{
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Other%20Events/Tink-Her-Hack%20Poster%20Draft.png?updatedAt=1738226589827",
        content: "he TINK-HER-HACK 2.0 hackathon, organized by AIDA in association with TinkerHub at Jyothi Engineering College, was an empowering and inspiring event exclusively for women. The hackathon aimed to encourage and support female students in the field of technology, providing them with a platform to showcase their skills and creativity. Participants worked collaboratively in teams to develop innovative solutions to real-world problems, guided by experienced mentors. The event featured a series of workshops and interactive sessions that enhanced the participants' technical knowledge and problem-solving abilities. TINKHERHACK concluded with impressive project presentations, and the top teams were awarded attractive prizes."
    },{
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Other%20Events/tink-her-hack%203.0.jpg?updatedAt=1738226588543",
        content: "The TINK-HER-HACK 3.0 hackathon, organized by AIDA in collaboration with TinkerHub at Jyothi Engineering College, was a remarkable event dedicated to empowering women in technology. The hackathon brought together female students from various disciplines to collaborate and create innovative solutions to real-world challenges. Throughout the event, participants received guidance and mentorship from experienced professionals, which significantly enhanced their skills and confidence. The hackathon included a series of workshops and interactive sessions, providing valuable insights into the latest technologies and tools. The event concluded with impressive project demonstrations, where teams showcased their creative and impactful solutions. The top-performing teams were awarded attractive prizes, recognizing their hard work and ingenuity"
    },{
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202023%202.0/WhatsApp%20Image%202023-11-17%20at%2012.51.03.jpeg?updatedAt=1704173091336",
        content: "The VRCADE event, organized by AIDA at Jyothi Engineering College during THARANG, was an immersive and exhilarating experience for all attendees. The event offered participants a unique opportunity to get hands-on with the latest virtual reality (VR) technology by playing various games in a fully immersive VR environment. Students explored different VR applications and experienced the cutting-edge technology first-hand. The event created a fun and engaging atmosphere, allowing participants to learn about VR's potential in gaming and other fields."
    },{
        img: "https://ik.imagekit.io/AIDA/Past%20Events/Tharang%202023/VRcade-min.png?updatedAt=1697130368361",
        content: "The VRCADE event, hosted by AIDA at Jyothi Engineering College during THARANG, offered an exhilarating introduction to the world of virtual reality. Participants were provided with hands-on experience using the latest VR technology, engaging in various immersive games and activities. The event allowed students to explore the dynamic capabilities of VR, fostering both excitement and curiosity about the future of this technology. The interactive sessions were well-received, with attendees expressing enthusiasm for the realistic and immersive experiences provided by the VR setups"
    },
      
  ]

export default eventData;